minecraft_version=1.21.10
minecraft_version_range=[1.21.9,1.21.11)
forge_version=60.1.0
forge_version_range=[59.0.5,)
loader_version_range=[59,)
java_version=21
mod_id=better_screenshots
mod_name=Better ScreenShots
mod_license=GPL-3.0
mod_version=1.9+1.21.9-1.21.10
mod_group_id=dev.gdlev.better_screenshots
